### ISSUE TITLE
msbuild task fails when no AssemblyInfo file is present

### ISSUE THREAD

**Issue by PatrickKursawe** [GitTools/GitVersion#885]
I think this was introduced with 6caae2e11a7cc13ca8f46ad78a1461cc8f262cae
The AssemblyInfoBuilder picks the correct implementation based on the file suffix for *AssemblyInfo*, but if no such file is present, it tries to access the dictionary with a null key, resulting in an ArgumentNullException.

**Comment by asbjornu** [comment]
@PatrickKursawe I fixed a lot of things related to `AssemblyInfo` patching in #882. It's merged, but not released yet. Do you think it might remedy the problem you're seeing? If not, do you think you can create a test that illustrates the problem?

**Comment by PatrickKursawe** [comment]
Does not look like the faulty part was touched. A test project within its own repository is attached.
[VersionTaskBug.zip](https://github.com/GitTools/GitVersion/files/291170/VersionTaskBug.zip)

**Comment by tpluscode** [comment]
No biggie, but i still occurs in version `3.5.4`. 

FYI it also occurs when the assembly info file is not set to `BuildAction = Compile`

**Comment by asbjornu** [comment]
@tpluscode Yea, #882 isn't released yet.

@PatrickKursawe I'll hopefully have time to look at that test project some time this week.
